[project]
name = "cs4119-proj"
version = "0.1.0"
description = "CS4119 Project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.75.0",
]
[tool.isort]
profile = "black"
